### ISSUE TITLE
danjing.yaml 缺少平假名

### ISSUE THREAD

**Issue by poorich** [cxcn/danjing#8]
https://github.com/cxcn/danjing/blob/main/danjing.yaml

line 940

缺了そ た ち 及相关

**Comment by poorich** [comment]
趁机提个需求
能否把小写的假名作为长按跳出整合到正常假名的键位？
可以的话希望  ウヴゥ   はばぱ  这些能用一个键位给安排了
胡搞的一个例子（改自98五笔群的集成的xl皮肤，删了韩文改假名来着）：


```
  symbolsC1:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "あ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぁ", key_symbol_color: key_symbol_color}
      - {click: "い", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぃ", key_symbol_color: key_symbol_color}
      - {click: "う", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぅ", key_symbol_color: key_symbol_color}
      - {click: "え", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぇ", key_symbol_color: key_symbol_color}
      - {click: "お", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぉ", key_symbol_color: key_symbol_color}
      - {click: "ー"}
      - {click: K_back, width: 19}
      - {click: "か", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ゕ", key_symbol_color: key_symbol_color}
      - {click: "き"}
      - {click: "く"}
      - {click: "け", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ゖ", key_symbol_color: key_symbol_color}
      - {click: "こ"}
      - {click: "・"}
      - {click: K_symbolsC1, key_text_color: fyt, width: 19}
      - {click: "が"}
      - {click: "ぎ"}
      - {click: "ぐ"}
      - {click: "げ"}
      - {click: "ご"}
      - {click: "㍿"}
      - {click: K_symbolsC2x, width: 19}
      - {click: "さ"}
      - {click: "し"}
      - {click: "す"}
      - {click: "せ"}
      - {click: "そ"}
      - {click: "㍐"}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名1"
    width: 13.5
  symbolsC2:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "ざ"}
      - {click: "じ"}
      - {click: "ず"}
      - {click: "ぜ"}
      - {click: "ぞ"}
      - {click: "゛"}
      - {click: K_back, width: 19}
      - {click: "た"}
      - {click: "ち"}
      - {click: "つ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "っ", key_symbol_color: key_symbol_color}
      - {click: "て"}
      - {click: "と"}
      - {click: "゜"}
      - {click: K_symbolsC1, width: 19}
      - {click: "だ"}
      - {click: "ぢ"}
      - {click: "づ"}
      - {click: "で"}
      - {click: "ど"}
      - {click: "ゝ"}
      - {click: K_symbolsC3x, width: 19}
      - {click: "な"}
      - {click: "に"}
      - {click: "ぬ"}
      - {click: "ね"}
      - {click: "の"}
      - {click: "ゞ"}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名2"
    width: 13.5
  symbolsC3:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "は"}
      - {click: "ひ"}
      - {click: "ふ"}
      - {click: "へ"}
      - {click: "ほ"}
      - {click: "ヽ"}
      - {click: K_back, width: 19}
      - {click: "ば", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぱ", key_symbol_color: key_symbol_color}
      - {click: "び", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぴ", key_symbol_color: key_symbol_color}
      - {click: "ぶ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぷ", key_symbol_color: key_symbol_color}
      - {click: "べ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぺ", key_symbol_color: key_symbol_color}
      - {click: "ぼ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ぽ", key_symbol_color: key_symbol_color}
      - {click: "ヾ"}
      - {click: K_symbolsC2, width: 19}
      - {click: "ま"}
      - {click: "み"}
      - {click: "む"}
      - {click: "め"}
      - {click: "も"}
      - {click: "ヿ"}
      - {click: K_symbolsC4x, width: 19}
      - {click: "や", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ゃ", key_symbol_color: key_symbol_color}
      - {click: ""}
      - {click: "ゆ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ゅ", key_symbol_color: key_symbol_color}
      - {click: ""}
      - {click: "よ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ょ", key_symbol_color: key_symbol_color}
      - {click: ""}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名3"
    width: 13.5
  symbolsC4:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "ら"}
      - {click: "り"}
      - {click: "る"}
      - {click: "れ"}
      - {click: "ろ"}
      - {click: ""}
      - {click: K_back, width: 19}
      - {click: "わ"}
      - {click: "ゐ"}
      - {click: ""}
      - {click: "ゑ"}
      - {click: "を"}
      - {click: "ん"}
      - {click: K_symbolsC3, width: 19}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: K_symbolsC5x, width: 19}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名4"
    width: 13.5
  symbolsC5:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "ア", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ァ", key_symbol_color: key_symbol_color}
      - {click: "イ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ィ", key_symbol_color: key_symbol_color}
      - {click: "ウ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ゥ", key_symbol_color: key_symbol_color}
      - {click: "エ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ェ", key_symbol_color: key_symbol_color}
      - {click: "オ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ォ", key_symbol_color: key_symbol_color}
      - {click: "ヴ"}
      - {click: K_back, width: 19}
      - {click: "カ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ヵ", key_symbol_color: key_symbol_color}
      - {click: "キ"}
      - {click: "ク", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇰ", key_symbol_color: key_symbol_color}
      - {click: "ケ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ヶ", key_symbol_color: key_symbol_color}
      - {click: "コ"}
      - {click: "ヶ"}
      - {click: K_symbolsC4, width: 19}
      - {click: "ガ"}
      - {click: "ギ"}
      - {click: "グ"}
      - {click: "ゲ"}
      - {click: "ゴ"}
      - {click: "・"}
      - {click: K_symbolsC6x, key_text_color: fyt, width: 19}
      - {click: "サ"}
      - {click: "シ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇱ", key_symbol_color: key_symbol_color}
      - {click: "ス", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇲ", key_symbol_color: key_symbol_color}
      - {click: "セ"}
      - {click: "ソ"}
      - {click: "ー"}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名5"
    width: 13.5
  symbolsC6:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "ザ"}
      - {click: "ジ"}
      - {click: "ズ"}
      - {click: "ゼ"}
      - {click: "ゾ"}
      - {click: ""}
      - {click: K_back, width: 19}
      - {click: "タ"}
      - {click: "チ"}
      - {click: "ツ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ッ", key_symbol_color: key_symbol_color}
      - {click: "テ"}
      - {click: "ト", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇳ", key_symbol_color: key_symbol_color}
      - {click: ""}
      - {click: K_symbolsC5, key_text_color: fyt, width: 19}
      - {click: "ダ"}
      - {click: "ヂ"}
      - {click: "ヅ"}
      - {click: "デ"}
      - {click: "ド"}
      - {click: "・"}
      - {click: K_symbolsC7x, key_text_color: fyt, width: 19}
      - {click: "ナ"}
      - {click: "ニ"}
      - {click: "ヌ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇴ", key_symbol_color: key_symbol_color}
      - {click: "ネ"}
      - {click: "ノ"}
      - {click: "ー"}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名6"
    width: 13.5
  symbolsC7:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "ハ"}
      - {click: "ヒ"}
      - {click: "フ"}
      - {click: "ヘ"}
      - {click: "ホ"}
      - {click: ""}
      - {click: K_back, width: 19}
      - {click: "バ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "パ", key_symbol_color: key_symbol_color}
      - {click: "ビ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ピ", key_symbol_color: key_symbol_color}
      - {click: "ブ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "プ", key_symbol_color: key_symbol_color}
      - {click: "ベ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ペ", key_symbol_color: key_symbol_color}
      - {click: "ボ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ポ", key_symbol_color: key_symbol_color}
      - {click: "ㇷ゚"}
      - {click: K_symbolsC6, key_text_color: fyt, width: 19}
      - {click: "マ"}
      - {click: "ミ"}
      - {click: "ム", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇺ", key_symbol_color: key_symbol_color}
      - {click: "メ"}
      - {click: "モ"}
      - {click: "・"}
      - {click: K_symbolsC8x, key_text_color: fyt, width: 19}
      - {click: "ヤ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ャ", key_symbol_color: key_symbol_color}
      - {click: ""}
      - {click: "ユ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ュ", key_symbol_color: key_symbol_color}
      - {click: ""}
      - {click: "ヨ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ョ", key_symbol_color: key_symbol_color}
      - {click: "ー"}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名7"
    width: 13.5
  symbolsC8:
    ascii_mode: 1
    author: flypy.com
    key_text_offset_y: *DtextY
    keys:
      - {click: "ラ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇻ", key_symbol_color: key_symbol_color}
      - {click: "リ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇼ", key_symbol_color: key_symbol_color}
      - {click: "ル", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇽ", key_symbol_color: key_symbol_color}
      - {click: "レ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇾ", key_symbol_color: key_symbol_color}
      - {click: "ロ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ㇿ", key_symbol_color: key_symbol_color}
      - {click: ""}
      - {click: K_back, width: 19}
      - {click: "ワ", key_text_offset_x: 3, key_symbol_offset_x: -15, key_symbol_offset_y: 14, long_click: "ヮ", key_symbol_color: key_symbol_color}
      - {click: "ヰ"}
      - {click: ""}
      - {click: "ヱ"}
      - {click: "ヲ"}
      - {click: "ン"}
      - {click: K_symbolsC7, key_text_color: fyt, width: 19}
      - {click: "ヷ"}
      - {click: "ヸ"}
      - {click: ""}
      - {click: "ヹ"}
      - {click: "ヺ"}
      - {click: "・"}
      - {click: K_symbolsC8x, key_text_color: fyt, width: 19}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: ""}
      - {click: "ー"}
      - {click: BackSpace, width: 19}
      - {click: K_symbols70, width: 12.5}
      - {click: K_symbols80, width: 12.5}
      - {click: K_symbols90, width: 12.5}
      - {click: K_symbolsA0, width: 12.5}
      - {click: K_symbolsB0, width: 12.5}
      - {click: K_symbolsC0, key_text_color: cdt, width: 12.5}
      - {click: K_symbolsD0, width: 12.5}
      - {click: K_symbols0z, width: 12.5}
    name: "假名8"
    width: 13.5
```
